# Site settings
name: Hi, I'm Yıldırım 👋
description: "Senior Android Developer"
url: ""

github_username:  ytam
linkedin_username: yildirimtam/
stack_of_username: 9054597
medium_username:  yildirimtam
email: yildirimtam@gmail.com

favicon_img: yes
favicon_img_path: "imgs/android.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
