# Site settings
name: Yıldırım Tam
description: "Mobile Application Developer"
url: ""

github_username:  ytam
linkedin_username: yildirimtam/
stack_of_username: 9054597
medium_username:  yildirimtam
email: yildirimtam@gmail.com

favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
